BEGIN;

ALTER TYPE application_type ADD VALUE IF NOT EXISTS 'renewal';

COMMIT;

BEGIN;

ALTER TABLE application
  ADD COLUMN IF NOT EXISTS assigned_room_id BIGINT REFERENCES room(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS eligibility_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS documents_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS payment_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS medical_clearance_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS safety_briefing_completed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS pass_issued BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS housing_conditions_confirmed BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS application_assigned_room_index ON application(assigned_room_id);

COMMIT;
